from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class GlossaryTerm:
    term: str
    category: str
    short_cn: str
    formula: str
    why_it_matters: str
    common_pitfall: str
    ui_location: str
    evidence: str


GLOSSARY_TERMS: tuple[GlossaryTerm, ...] = (
    GlossaryTerm(
        term="ITE",
        category="causal quantity",
        short_cn="个体处理效应，同一个用户接受 treatment 与不接受 treatment 的结果差。",
        formula="ITE_i = Y_i(1) - Y_i(0)",
        why_it_matters="uplift 建模想排序的本质对象。",
        common_pitfall="真实业务里同一个用户只能观测一个潜在结果，ITE 通常不可直接观测。",
        ui_location="指标评估 / 模型拆解 / Benchmark Dashboard",
        evidence="predictions.csv: uplift_score; known-CATE benchmark: true_uplift",
    ),
    GlossaryTerm(
        term="CATE",
        category="causal quantity",
        short_cn="条件平均处理效应，给定特征 X=x 时的平均增量效果。",
        formula="CATE(x)=E[Y(1)-Y(0)|X=x]",
        why_it_matters="把 treatment 效果从全局平均拆到人群/个体层面。",
        common_pitfall="如果 overlap 差，CATE 会变成高风险外推。",
        ui_location="模型拆解 / 指标评估",
        evidence="model deconstruction docs; paper benchmark PEHE/ATE rows",
    ),
    GlossaryTerm(
        term="ATE",
        category="causal quantity",
        short_cn="平均处理效应，全体样本接受 treatment 相比 control 的平均增量。",
        formula="ATE=E[Y(1)-Y(0)]",
        why_it_matters="回答整体策略是否有平均增益。",
        common_pitfall="ATE 好不代表 Top-K 策略好，也不代表 ROI 为正。",
        ui_location="Benchmark Dashboard",
        evidence="paper_benchmark_latest.json: ate_error",
    ),
    GlossaryTerm(
        term="PEHE",
        category="paper benchmark metric",
        short_cn="个体效应预测误差，衡量预测 uplift 和真实 CATE 的距离。",
        formula="PEHE=sqrt(mean((tau_hat(x)-tau(x))^2))",
        why_it_matters="IHDP/ACIC/known-CATE 里最像论文复现的核心指标，越低越好。",
        common_pitfall="真实线上没有 true CATE，所以 PEHE 只适合仿真/半合成 benchmark。",
        ui_location="Benchmark Dashboard / 模型拆解",
        evidence="reports/paper_benchmark_leaderboard_latest.csv: pehe_mean",
    ),
    GlossaryTerm(
        term="ATE error",
        category="paper benchmark metric",
        short_cn="平均处理效应误差，预测平均 uplift 与真实平均 uplift 的差。",
        formula="|mean(tau_hat)-mean(tau)|",
        why_it_matters="检验模型是否把整体 treatment effect 估偏。",
        common_pitfall="ATE error 低不代表 Top-K 排序好，需要和 PEHE/QINI 一起看。",
        ui_location="Benchmark Dashboard",
        evidence="reports/paper_benchmark_leaderboard_latest.csv: ate_error_mean",
    ),
    GlossaryTerm(
        term="QINI",
        category="ranking metric",
        short_cn="按 uplift score 排序后的累计增量曲线面积。",
        formula="Q(k)=Y_t(k)-Y_c(k)*N_t(k)/N_c(k)",
        why_it_matters="判断模型是否比随机策略更早找到 persuadable users。",
        common_pitfall="QINI 是排序指标，不看成本、预算、毛利和校准。",
        ui_location="指标评估 / Benchmark Dashboard",
        evidence="metrics.json:qini_score; paper_benchmark_latest.json:qini",
    ),
    GlossaryTerm(
        term="AUUC",
        category="ranking metric",
        short_cn="uplift curve 的面积，衡量多个投放比例下的整体排序质量。",
        formula="AUUC=integral U(p) dp",
        why_it_matters="和 QINI 一起看模型排序是否全局稳定。",
        common_pitfall="AUUC 好不代表业务最关心的 Top-K 一定好。",
        ui_location="指标评估 / Benchmark Dashboard",
        evidence="metrics.json:auuc_score; paper_benchmark_latest.json:auuc",
    ),
    GlossaryTerm(
        term="uplift@K",
        category="top-k metric",
        short_cn="只看会被投放的 Top-K 人群中的 observed uplift。",
        formula="E[Y|T=1,TopK]-E[Y|T=0,TopK]",
        why_it_matters="更贴近灰度投放和名单导出的实际人群。",
        common_pitfall="Top-K 样本少时方差高，必须看 CI 和 treatment/control 覆盖。",
        ui_location="指标评估 / Policy/ROI",
        evidence="metrics.json:top_k",
    ),
    GlossaryTerm(
        term="policy value",
        category="decision metric",
        short_cn="某个投放/路由/补贴策略实际能带来的期望价值。",
        formula="V(pi)=E[Y(pi(X))]",
        why_it_matters="把模型分数转成上线策略，而不是只看模型排名。",
        common_pitfall="没有成本、价值和 holdout 口径时，policy value 容易过乐观。",
        ui_location="Policy/ROI / Benchmark Dashboard",
        evidence="metrics.json:policy_best; reports/*policy*.json",
    ),
    GlossaryTerm(
        term="bootstrap CI",
        category="uncertainty",
        short_cn="重复抽样得到指标置信区间，用来判断结果是否稳定。",
        formula="CI=percentile(metric(sample_b), [2.5%,97.5%])",
        why_it_matters="避免把一次随机划分的噪声当成模型优势。",
        common_pitfall="CI 不能修复数据设计偏差，只能描述当前样本波动。",
        ui_location="指标评估 / Benchmark Dashboard",
        evidence="metrics.json:bootstrap; paper benchmark *_ci_low/_ci_high",
    ),
    GlossaryTerm(
        term="propensity",
        category="diagnostic",
        short_cn="样本被分配到 treatment 的概率 e(x)。",
        formula="e(x)=P(T=1|X=x)",
        why_it_matters="DR/R/DML/OPE 都依赖 treatment assignment 机制。",
        common_pitfall="propensity 接近 0/1 会导致高方差和不可支持外推。",
        ui_location="诊断 / 指标评估",
        evidence="diagnostics; metrics.json:overlap_trim",
    ),
    GlossaryTerm(
        term="overlap",
        category="diagnostic",
        short_cn="同一类用户同时有 treatment 和 control 支持，也叫 common support。",
        formula="0 < e(x) < 1",
        why_it_matters="没有 overlap，模型只能外推，因果解释不可信。",
        common_pitfall="整体 treatment rate 正常不代表每个 segment 都有 overlap。",
        ui_location="诊断 / Evidence Dashboard",
        evidence="metrics.json:overlap_trim; diagnostics warnings",
    ),
    GlossaryTerm(
        term="DR Learner",
        category="model family",
        short_cn="Doubly Robust learner，同时使用 outcome model 和 propensity model 构造伪标签。",
        formula="phi=mu1-mu0+T(Y-mu1)/e-(1-T)(Y-mu0)/(1-e)",
        why_it_matters="观测数据、selection bias 场景下的强基线。",
        common_pitfall="如果 outcome 和 propensity 都差，DR 仍然会失真。",
        ui_location="模型 / 模型拆解",
        evidence="docs/model_deconstruction/DRLearnerGBM.md; nuisance diagnostics",
    ),
    GlossaryTerm(
        term="R Learner / DML",
        category="model family",
        short_cn="先残差化 outcome 和 treatment，再学习 treatment residual 对 outcome residual 的影响。",
        formula="min_tau sum((Y-m(X))-(T-e(X))*tau(X))^2",
        why_it_matters="正交化能降低 nuisance 模型误差对 CATE 的一阶影响。",
        common_pitfall="nuisance 质量和 overlap 仍然是硬约束。",
        ui_location="模型 / Evidence Dashboard",
        evidence="reports/nuisance_diagnostics_smoke_latest.json",
    ),
    GlossaryTerm(
        term="OPE",
        category="policy evaluation",
        short_cn="Off-Policy Evaluation，用历史日志评估一个尚未上线的新策略。",
        formula="IPS/SNIPS/DR estimates of V(pi)",
        why_it_matters="offline benchmark 到 online A/B 之间的桥。",
        common_pitfall="没有 logged propensity 或 coverage 很低时，OPE 不可靠。",
        ui_location="Policy/ROI / Evidence Dashboard",
        evidence="reports/ope_engine_smoke_latest.json; reports/llm_routing_ope_smoke_latest.json",
    ),
    GlossaryTerm(
        term="IPS / SNIPS / DR OPE",
        category="policy evaluation",
        short_cn="IPS 用 propensity 反事实加权，SNIPS 做自归一化，DR 加 reward model 修正。",
        formula="V_DR=mu(pi(x),x)+1{a=pi(x)}/p(a|x)*(r-mu(a,x))",
        why_it_matters="能解释一个新 policy 的离线价值和方差风险。",
        common_pitfall="clipping 能降方差但会引入偏差，需要 sensitivity。",
        ui_location="Policy/ROI / Evidence Dashboard",
        evidence="reports/ope_engine_smoke_latest.json",
    ),
    GlossaryTerm(
        term="ESS",
        category="policy evaluation",
        short_cn="Effective Sample Size，有效样本量，衡量 OPE/IPW 权重是否过度集中。",
        formula="ESS=(sum w)^2/sum(w^2)",
        why_it_matters="ESS 太低说明估计主要靠少数高权重样本。",
        common_pitfall="样本量大但 ESS 低，离线评估仍然不可信。",
        ui_location="Evidence Dashboard",
        evidence="reports/ope_engine_smoke_latest.json; nuisance diagnostics",
    ),
    GlossaryTerm(
        term="CFRNet",
        category="deep model",
        short_cn="在 TARNet outcome heads 上加入 representation balance 的深度 CATE 模型。",
        formula="loss=factual_loss + alpha * IPM(phi_t, phi_c)",
        why_it_matters="适合 treatment/control 分布偏移明显的深度 uplift baseline。",
        common_pitfall="balance loss 不能替代真实 overlap；alpha 过大会伤 outcome fit。",
        ui_location="模型拆解 / Benchmark Dashboard",
        evidence="docs/model_deconstruction/CFRNet.md; reports/deep_model_training_evidence_latest.json",
    ),
    GlossaryTerm(
        term="DragonNet",
        category="deep model",
        short_cn="共享表征 + y0/y1 heads + propensity head，并可加 targeted regularization。",
        formula="loss=outcome_loss + alpha*propensity_loss + beta*targeted_reg",
        why_it_matters="把 treatment assignment 信息显式放进网络训练。",
        common_pitfall="propensity head 学得好不等于 CATE 排序一定好。",
        ui_location="模型拆解 / Benchmark Dashboard",
        evidence="docs/model_deconstruction/DragonNet.md",
    ),
    GlossaryTerm(
        term="EFIN",
        category="deep model",
        short_cn="Explicit Feature Interaction-aware Uplift Network，强调用户特征与 treatment 的交互。",
        formula="interaction(user_embedding, treatment_embedding) -> uplift heads",
        why_it_matters="营销/推荐类表格数据里 treatment-aware interaction 很重要。",
        common_pitfall="官方实现 GPL-3.0，只能参考思想，不能默认复制代码。",
        ui_location="模型拆解 / Benchmark Dashboard",
        evidence="docs/model_deconstruction/EFIN.md",
    ),
    GlossaryTerm(
        term="DESCN",
        category="deep model",
        short_cn="Deep Entire Space Cross Networks，偏 classification 的 entire-space uplift 架构。",
        formula="shared/cross heads model treatment, control and effect spaces",
        why_it_matters="适合转化、访问等 0/1 outcome 的工业 uplift 场景。",
        common_pitfall="不适合默认跑 regression IHDP，所以需要 task-aware skip。",
        ui_location="模型拆解 / Benchmark Dashboard",
        evidence="docs/model_deconstruction/DESCN.md; failure attribution",
    ),
    GlossaryTerm(
        term="multi-treatment uplift",
        category="extension",
        short_cn="不只有 treat/control，而是在多个 action 中估计每个动作相对 control 的增量。",
        formula="tau_a(x)=E[Y(a)-Y(0)|X=x]",
        why_it_matters="适合多券档、多触达渠道、LLM 多动作 routing。",
        common_pitfall="动作空间越大，logged policy coverage 和 OPE 越关键。",
        ui_location="多 Treatment / Policy/ROI",
        evidence="reports/multi_treatment_benchmark_latest.json",
    ),
    GlossaryTerm(
        term="dose-response",
        category="extension",
        short_cn="treatment 是连续剂量，比如折扣力度、出价、补贴金额。",
        formula="mu(x,d)=E[Y|X=x,D=d]",
        why_it_matters="工业里很多干预不是二元开关，而是连续强度决策。",
        common_pitfall="推荐剂量不能超出历史支持范围，否则是危险外推。",
        ui_location="剂量响应 / Policy/ROI",
        evidence="reports/continuous_treatment_policy_smoke_latest.json",
    ),
    GlossaryTerm(
        term="evidence manifest",
        category="governance",
        short_cn="一次训练/benchmark 的证据清单，包含配置、数据指纹、指标、预测和环境。",
        formula="run evidence = config + metrics + predictions + hashes + env",
        why_it_matters="让每个 claim 都能追到文件，而不是只靠口头描述。",
        common_pitfall="只有指标没有 manifest，复现和评审都站不住。",
        ui_location="Evidence Dashboard / 历史",
        evidence="runs/*/evidence_manifest.json; reports/paper_benchmark_manifest_latest.json",
    ),
    GlossaryTerm(
        term="run diff",
        category="governance",
        short_cn="比较本次 benchmark 和上一次 benchmark 的指标变化。",
        formula="delta_metric = current_metric - previous_metric",
        why_it_matters="防止新功能悄悄让 benchmark 退化。",
        common_pitfall="单 seed diff 只能作为烟测信号，多 seed 才适合严肃判断。",
        ui_location="Benchmark Dashboard / Evidence Dashboard",
        evidence="reports/paper_benchmark_run_diff_latest.json",
    ),
    GlossaryTerm(
        term="readiness gate",
        category="governance",
        short_cn="上线前的闸门，综合指标、CI、overlap、OPE、policy value 和 artifact 完整性。",
        formula="readiness = metrics + uncertainty + diagnostics + artifacts",
        why_it_matters="把 demo 模型和可试点模型区分开。",
        common_pitfall="只看 leaderboard 第一名就上线，是 uplift 项目的高风险做法。",
        ui_location="Evidence Dashboard / 历史",
        evidence="readiness.json; promotion.json; validate_latest_artifacts.py",
    ),
    GlossaryTerm(
        term="Regression Warning Audit",
        category="governance",
        short_cn="把 smoke、benchmark、OPE、scenario compare 和 evidence store 里的风险信号汇总成上线前审计表。",
        formula="warning = metric risk + readiness risk + support risk + evidence risk",
        why_it_matters="让失败、研究态和不能上线的证据显式可见，避免只展示好看的 leaderboard。",
        common_pitfall="warning 多不等于系统失败；真正的问题是 warning 没有 owner、补实验和 promotion decision。",
        ui_location="Evidence Dashboard",
        evidence="reports/regression_warning_audit_latest.json; docs/DEEPUplift_REGRESSION_WARNING_AUDIT.md",
    ),
    GlossaryTerm(
        term="launch gate",
        category="governance",
        short_cn="一次模型或策略是否可以进入试点/上线的总门禁状态。",
        formula="launch_gate = review_required if any(high warning) else monitor",
        why_it_matters="把能跑、能演示、能试点、能上线分开。",
        common_pitfall="review_required 不是失败标签，而是需要根因、owner 和补实验的上线评审状态。",
        ui_location="Evidence Dashboard",
        evidence="reports/regression_warning_audit_latest.json:summary.launch_gate",
    ),
    GlossaryTerm(
        term="promotion decision",
        category="governance",
        short_cn="每条 warning 对模型晋级的影响：block_promotion、review_before_promotion 或 monitor。",
        formula="severity high -> block; medium -> review; low -> monitor",
        why_it_matters="面试/评审时可以清楚说明哪些结果不能上线，哪些只是需要观察。",
        common_pitfall="把所有 warning 都当成同等严重会让评审失焦；需要按 severity 和业务风险分层。",
        ui_location="Evidence Dashboard",
        evidence="reports/regression_warning_audit_latest.csv:promotion_decision",
    ),
    GlossaryTerm(
        term="next experiment",
        category="governance",
        short_cn="针对某个 warning 推荐的下一步验证动作，比如多 seed、bootstrap、OPE、shadow、holdout 或 A/B。",
        formula="next_experiment = risk_type -> validation_action",
        why_it_matters="把风险清单转成可执行路线图，而不是停留在问题罗列。",
        common_pitfall="没有把风险映射到实验，就无法推进到上线试点。",
        ui_location="Evidence Dashboard",
        evidence="reports/regression_warning_audit_latest.csv:next_experiment",
    ),
    GlossaryTerm(
        term="owner role",
        category="governance",
        short_cn="负责处理 warning 的角色，例如 ML/benchmark owner、business owner、experimentation owner 或 platform owner。",
        formula="owner_role = domain(signal)",
        why_it_matters="工业评审关心的不只是模型对错，还关心谁负责补证据、谁决定是否上线。",
        common_pitfall="没有 owner 的风险项会长期悬空，最后变成上线事故或面试追问漏洞。",
        ui_location="Evidence Dashboard",
        evidence="reports/regression_warning_audit_latest.csv:owner_role",
    ),
    GlossaryTerm(
        term="promotion launch card",
        category="governance",
        short_cn="把一组 warning 聚合成上线评审卡，明确 decision、owner、safe/unsafe claim 和上线前补实验。",
        formula="card = grouped warnings -> decision + owner + safe_claim + next_experiment + rollout gates",
        why_it_matters="评审和面试里最怕只列风险不推进；promotion card 把风险变成可执行 launch review。",
        common_pitfall="card 不是上线批准书；block 或 review 状态仍然需要 shadow、holdout、A/B 或 OPE 证据。",
        ui_location="Evidence Dashboard",
        evidence="reports/promotion_launch_cards_latest.json; docs/DEEPUplift_PROMOTION_LAUNCH_CARDS.md",
    ),
    GlossaryTerm(
        term="objective diagnostics",
        category="model",
        short_cn="把模型 objective/loss term 映射到可观测诊断、失败信号和 benchmark claim。",
        formula="objective card = loss terms + code path + diagnostics + safe/unsafe claim",
        why_it_matters="深度 uplift 面试不能只背模型名；要能说明每个 loss term 为什么存在、怎么验证、什么时候会失败。",
        common_pitfall="loss 下降不等于 CATE 好，CATE 好也不等于 policy value 或 ROI 好。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_objective_diagnostics_latest.json; docs/DEEPUplift_DEEP_MODEL_OBJECTIVE_DIAGNOSTICS.md",
    ),
    GlossaryTerm(
        term="algorithm claim ledger",
        category="governance",
        short_cn="把算法结论绑定到公式、源码路径、benchmark verdict、license gate 和 safe/unsafe claim 的台账。",
        formula="claim = model + formula + code_refs + evidence_refs + safe_claim + unsafe_claim",
        why_it_matters="面试和评审最容易被追问“凭什么这么说”；claim ledger 让每句话都能追到证据层级。",
        common_pitfall="claim ledger 不是自动背书；如果 evidence_level 只是 smoke 或 source_only，就不能包装成上线结论。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/algorithm_claim_ledger_latest.json; docs/DEEPUplift_ALGORITHM_CLAIM_LEDGER.md",
    ),
    GlossaryTerm(
        term="paper reproduction gap ledger",
        category="governance",
        short_cn="把论文/开源来源、本地复现程度、license 风险、benchmark 证据和剩余 gap 放到一起的台账。",
        formula="reproduction_gap = source + license + local_scope + proof_level + gaps + validation_needed",
        why_it_matters="论文复现面试最怕把 citation 说成 full reproduction；这个台账让复现等级和剩余差距可审计。",
        common_pitfall="paper-level benchmark candidate 仍不是生产效果证明；GPL/unknown license 也不能直接复制进默认仓库。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/paper_reproduction_gap_ledger_latest.json; docs/DEEPUplift_PAPER_REPRODUCTION_GAP_LEDGER.md",
    ),
    GlossaryTerm(
        term="model evidence promotion matrix",
        category="governance",
        short_cn="把每个模型的源码、复现、benchmark、loss 诊断、license 和上线 claim 汇总成推广等级矩阵。",
        formula="promotion_matrix = model + evidence_stage + promotion_tier + safe_claim + blocked_claim + next_evidence_step",
        why_it_matters="它回答“这个模型现在到底能讲到什么程度”：面试能讲、benchmark 能比、上线试点还缺什么，一张表说清楚。",
        common_pitfall="promotion tier 不是生产放行；T0/T1 仍然需要业务 holdout、OPE、A/B 和 rollback gate。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/model_evidence_promotion_matrix_latest.json; docs/DEEPUplift_MODEL_EVIDENCE_PROMOTION_MATRIX.md",
    ),
    GlossaryTerm(
        term="model upgrade recipe card",
        category="governance",
        short_cn="把一个模型下一步升级证据的实验假设、命令、指标、通过门禁和失败处理写成卡片。",
        formula="recipe = hypothesis + command + metrics_to_watch + pass_gate + fail_action + expected_artifacts",
        why_it_matters="它让“下一步怎么优化”变成可执行计划，面试和评审时能直接说明如何从 T2/T3 升级到 T0/T1。",
        common_pitfall="recipe 只是实验计划，不是实验结果；执行后必须刷新 benchmark、warning audit 和 promotion matrix。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/model_upgrade_recipe_cards_latest.json; docs/DEEPUplift_MODEL_UPGRADE_RECIPE_CARDS.md",
    ),
    GlossaryTerm(
        term="deep model telemetry gap matrix",
        category="model",
        short_cn="把深度模型每个 loss term 映射到当前信号、缺失 telemetry、实现 hook、pass gate 和失败处理的矩阵。",
        formula="telemetry_gap = loss_term + current_signal + missing_telemetry + hook + pass_gate + fail_action",
        why_it_matters="它让 CFRNet/DragonNet/EFIN/DESCN 的胜负归因不止停在 leaderboard，而能追到 representation、propensity、attention 或 head-level 证据。",
        common_pitfall="telemetry gap matrix 是观测性和下一步实现计划，不是新的 benchmark 结果；执行后仍要刷新训练、benchmark 和 promotion artifacts。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_telemetry_gap_matrix_latest.json; docs/DEEPUplift_DEEP_MODEL_TELEMETRY_GAP_MATRIX.md",
    ),
    GlossaryTerm(
        term="deep model telemetry smoke",
        category="model",
        short_cn="从最新深度模型 run artifacts 读取 loss history、prediction spread、Top-K known-CATE signal、metrics 和 manifest 的轻量验证。",
        formula="telemetry_smoke = train_history + predictions + metrics + manifest -> basic pass + advanced hook gaps",
        why_it_matters="它证明当前 evidence pipe 已经能读到基础训练/预测信号，同时明确高级 phi/e_hat/attention/head hook 仍需要后续 guarded 实现。",
        common_pitfall="basic telemetry pass 不是 paper-level 胜利；它只是说明可观测链路可跑，仍需 gap matrix 里的高级 hook 和 benchmark 验证。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_telemetry_smoke_latest.json; docs/DEEPUplift_DEEP_MODEL_TELEMETRY_SMOKE.md",
    ),
    GlossaryTerm(
        term="deep model forward hook contract",
        category="model",
        short_cn="在真正改模型 forward/loss 前，先定义要导出的 tensor keys、artifact files、smoke test、pass gate、fallback 和兼容规则。",
        formula="hook_contract = tensor_schema + artifact_schema + producer + consumer + pass_gate + fallback",
        why_it_matters="它把 CFRNet 的 phi_x、DragonNet 的 e_hat/tarreg、EFIN 的 attention/path、DESCN 的 heads/loss components 变成可实现、可验收的源码改造契约。",
        common_pitfall="forward hook contract 不是已经完成高级 telemetry；它是下一步 guarded refactor 的 schema 和门禁。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_forward_hook_contracts_latest.json; docs/DEEPUplift_DEEP_MODEL_FORWARD_HOOK_CONTRACTS.md",
    ),
    GlossaryTerm(
        term="deep model forward hook smoke",
        category="model",
        short_cn="在小批 synthetic tensor 上真实执行深度模型 forward，并把 phi_x、e_hat、tarreg、attention、heads 等高级 hook 产物写成 sidecar artifacts。",
        formula="hook_smoke = model.forward(batch) -> tensor_exports + sidecar_artifacts + pass_gate",
        why_it_matters="它把 hook contract 从计划推进到可跑证据，同时保持默认模型 API 不变，避免为了可解释性导出破坏现有 demo。",
        common_pitfall="forward hook smoke 只是小批可执行证明，不等于 per-epoch trainer telemetry 或 paper-level benchmark 结论。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_forward_hook_smoke_latest.json; docs/DEEPUplift_DEEP_MODEL_FORWARD_HOOK_SMOKE.md",
    ),
    GlossaryTerm(
        term="deep model hook training bridge",
        category="model",
        short_cn="把 forward hook sidecar 和训练 run/manifest 连接起来，定义下一步 trainer-level per-epoch telemetry 的字段、artifact、pass gate 和 fail action。",
        formula="hook_training_bridge = hook_sidecar + train_history + evidence_manifest -> epoch_columns + pass_gate",
        why_it_matters="它让 CFRNet/DragonNet/EFIN/DESCN 从一次性 tensor export 安全升级到训练期可观测证据，避免直接大改模型源码带来兼容风险。",
        common_pitfall="training bridge 是迁移契约，不是已经完成 per-epoch hook；真正推广前仍要实现 optional collector、刷新 benchmark 并做 ablation。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_hook_training_bridge_latest.json; docs/DEEPUplift_DEEP_MODEL_HOOK_TRAINING_BRIDGE.md",
    ),
    GlossaryTerm(
        term="deep model trainer collector smoke",
        category="model",
        short_cn="在 tiny training loop 中按 epoch 导出深度模型内部 telemetry，例如 representation balance、propensity/tarreg、attention/path、heads/constraints。",
        formula="trainer_collector_smoke = train_epoch(model) -> advanced_epoch_telemetry + sidecar_artifacts",
        why_it_matters="它把 hook bridge 从设计推进到可执行训练期证据，让面试官看到不是只导出一次 forward tensor，而是能沿训练过程观测模型内部机制。",
        common_pitfall="trainer collector smoke 不是生产训练监控，也不是论文 ablation；它证明采集路径可跑，下一步仍要连接 PEHE/QINI/policy movement。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_trainer_collector_smoke_latest.json; docs/DEEPUplift_DEEP_MODEL_TRAINER_COLLECTOR_SMOKE.md",
    ),
    GlossaryTerm(
        term="deep model telemetry-benchmark linkage",
        category="model",
        short_cn="把深度模型训练期内部 telemetry 和 paper/tuned benchmark 胜负、baseline verdict、failure hypothesis、next ablation 连接起来的证据表。",
        formula="linkage = trainer_telemetry + paper_scorecard + tuned_battle + baseline_context -> safe_claim + next_ablation",
        why_it_matters="它让深度模型失败归因从单纯看 leaderboard 升级为机制级评审：这个 loss term 有什么内部信号、benchmark 怎么表现、下一步用什么 ablation 证明因果关系。",
        common_pitfall="linkage 只证明证据可 join，不证明内部指标导致了 benchmark 提升；真正的因果 claim 还需要 ablation 或多 seed 曲线联动。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_telemetry_benchmark_linkage_latest.json; docs/DEEPUplift_DEEP_MODEL_TELEMETRY_BENCHMARK_LINKAGE.md",
    ),
    GlossaryTerm(
        term="deep model telemetry ablation gate",
        category="model",
        short_cn="把 telemetry-benchmark linkage 的下一步实验升级成可执行消融门禁：变体覆盖、指标、通过条件、失败处理和 claim 边界。",
        formula="ablation_gate = linkage + required_variants + metrics + pass_gate + fail_action",
        why_it_matters="它回答面试官最容易追问的下一句：你说这个内部机制重要，那要跑什么 ablation 才能把 safe claim 升级，哪些缺口还不能讲过头。",
        common_pitfall="ablation gate 是实验门禁，不是已经证明消融胜利；缺少 variant 或 baseline 仍更强时，blocked claim 必须继续保留。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_telemetry_ablation_gate_latest.json; docs/DEEPUplift_DEEP_MODEL_TELEMETRY_ABLATION_GATE.md",
    ),
    GlossaryTerm(
        term="deep model ablation interpretation",
        category="model",
        short_cn="读取 tuned benchmark 中 default-vs-variant 的 PEHE/QINI/policy/loss 变化，把每个消融变体解释成 safe claim、blocked claim 和面试话术。",
        formula="ablation_interpretation = tuned_benchmark + ablation_gate -> metric_movement + safe_claim + blocked_claim",
        why_it_matters="它把“消融变体已经能跑”升级成“消融结果能不能支持机制 claim”，避免把 variant coverage 误讲成论文级证明。",
        common_pitfall="一个 variant 跑通不代表机制被证明；即使相对 default 有提升，如果仍输给 T/DR baseline，也只能作为局部证据或 tradeoff 讲。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_interpretation_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_INTERPRETATION.md",
    ),
    GlossaryTerm(
        term="deep model ablation promotion matrix",
        category="governance",
        short_cn="把消融解读结果升级成 claim tier、promotion decision、default-or-variant 推荐和 blocked claim 的矩阵。",
        formula="ablation_promotion = ablation_interpretation + model_promotion_context -> claim_tier + promotion_decision + blocked_claim",
        why_it_matters="它回答“这个消融 variant 到底能不能讲成面试亮点”：能讲的是本地机制证据、tradeoff case，还是只能保留为覆盖证据。",
        common_pitfall="B/C tier 不是 SOTA 或生产效果；即使 variant 比 default 好，只要 baseline 更强或样本/seed 太小，就不能宣传成上线结论。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_promotion_matrix_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_PROMOTION_MATRIX.md",
    ),
    GlossaryTerm(
        term="deep model ablation next experiment plan",
        category="governance",
        short_cn="把每个消融 variant 的 claim tier 转成下一步实验命令、指标、通过门禁、失败处理和 owner。",
        formula="next_experiment = claim_tier + failure_attribution -> command + metrics + pass_gate + fail_action",
        why_it_matters="它让“下一步怎么优化”不再是口头调参，而是可执行、可回归、可面试讲清楚的实验路线。",
        common_pitfall="next experiment plan 是实验计划，不是实验结果；跑完后必须刷新 benchmark、ablation interpretation 和 promotion matrix。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_next_experiment_plan_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_NEXT_EXPERIMENT_PLAN.md",
    ),
    GlossaryTerm(
        term="deep model ablation command contract",
        category="governance",
        short_cn="审计 next-experiment 命令是否被当前 benchmark runner CLI 支持，并为每个 variant 保留可执行 fallback。",
        formula="command_contract = planned_command_flags ∩ runner_supported_flags + runnable_fallback_command",
        why_it_matters="它防止把路线图命令包装成已经可执行的实验；面试中可以清楚区分规划型 adapter 和当前可跑证据。",
        common_pitfall="不要把 planning-only command 当成 benchmark 结果；fallback smoke 只能证明可执行边界，不能替代多 seed paper-level benchmark。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_command_contract_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_COMMAND_CONTRACT.md",
    ),
    GlossaryTerm(
        term="deep model ablation command contract smoke",
        category="governance",
        short_cn="抽样执行 command contract 里的 fallback command，并用隔离 output prefix 证明命令能跑且不覆盖主 benchmark latest。",
        formula="contract_smoke = sample(runnable_fallback_command) -> runner_manifest + no_update_latest",
        why_it_matters="它把“命令看起来能跑”升级成“命令实际跑过”，但又避免小样本 smoke 覆盖完整 benchmark 证据。",
        common_pitfall="smoke 只证明可执行性，不证明模型效果稳定；效果 claim 仍要看多 seed benchmark、promotion matrix 和上线实验。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_command_contract_smoke_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_COMMAND_CONTRACT_SMOKE.md",
    ),
    GlossaryTerm(
        term="deep model ablation recommended command smoke",
        category="governance",
        short_cn="抽样执行 runner-native recommended command，证明 --models、--include-variants、--emit-battle-cards 这些新 CLI alias 真能跑。",
        formula="recommended_smoke = sample(recommended_command) + safe_overrides -> runner_manifest + no_update_latest",
        why_it_matters="它把“推荐实验命令”从路线图升级为当前 runner 原生支持的可执行证据，减少面试或评审中的 adapter 解释成本。",
        common_pitfall="它仍然是小样本命令 smoke，不等于完整 tuned benchmark 或 paper-level benchmark；效果 claim 仍要看 leaderboard、CI 和 promotion gate。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_recommended_command_smoke_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_RECOMMENDED_COMMAND_SMOKE.md",
    ),
    GlossaryTerm(
        term="deep model ablation command smoke coverage",
        category="governance",
        short_cn="把 command contract、fallback smoke 和 runner-native recommended smoke 合成覆盖率表，区分已执行 smoke 和只具备 contract-ready 的 backlog。",
        formula="smoke_coverage = command_contract + fallback_smoke + recommended_smoke -> coverage_status + next_action",
        why_it_matters="它让证据边界更诚实：runner-supported 代表 CLI 支持，smoke-covered 代表真实安全执行并产出 manifest，两者不能混为一谈。",
        common_pitfall="coverage report 不是模型效果报告；未 smoke 的 contract-ready 行不能讲成已经跑过，已 smoke 的行也只能证明可执行性。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_command_smoke_coverage_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_COMMAND_SMOKE_COVERAGE.md",
    ),
    GlossaryTerm(
        term="deep model ablation command smoke coverage diff",
        category="governance",
        short_cn="把 fallback-only smoke 覆盖率和当前 runner-native smoke 覆盖率做前后对比，说明本轮 evidence gate 为什么升级。",
        formula="coverage_diff = baseline_fallback_smoked -> current_any_smoked + gate_delta + per_variant_transition",
        why_it_matters="它让迭代成果可讲：从 1/9 fallback-smoked 到 9/9 current-smoked 是工程证据升级，不只是多了一张表。",
        common_pitfall="coverage diff 仍然只证明命令可执行和 evidence governance 成熟；模型胜负、paper-level claim 和上线 claim 仍要看 benchmark、promotion card 和线上实验。",
        ui_location="Model Deconstruction / Evidence Dashboard",
        evidence="reports/deep_model_ablation_command_smoke_coverage_diff_latest.json; docs/DEEPUplift_DEEP_MODEL_ABLATION_COMMAND_SMOKE_COVERAGE_DIFF.md",
    ),
    GlossaryTerm(
        term="regression warning triage",
        category="governance",
        short_cn="把 warning audit 的每条风险分到 risk family、claim boundary、action lane，区分 smoke-only caveat 和真正阻塞 pilot 的 launch blocker。",
        formula="warning_triage = warning_audit + promotion_cards -> risk_family + claim_boundary + action_lane + launch_blocking",
        why_it_matters="它让 warning 变成上线评审议程：哪些只是小样本 smoke 的解释边界，哪些必须补 holdout/OPE/overlap/ROI 实验后才能试点。",
        common_pitfall="triage 不是把 warning 洗白；launch_blocking=true 的行仍然阻塞 pilot，smoke-only 也不能被讲成质量证据。",
        ui_location="Evidence Dashboard / Agent",
        evidence="reports/regression_warning_triage_latest.json; docs/DEEPUplift_REGRESSION_WARNING_TRIAGE.md",
    ),
    GlossaryTerm(
        term="pilot readiness scorecard",
        category="governance",
        short_cn="把 promotion card 和 warning triage 汇总成试点门禁，给出 blocked、paper review、shadow candidate、monitor 四类决策。",
        formula="pilot_readiness = promotion_cards + warning_triage -> pilot_gate + readiness_score + rollback_conditions",
        why_it_matters="它把“这个模型能不能上线试点”从口头判断变成可审计 scorecard：下一步是修 blocker、做 paper-level 评审、进 shadow，还是只监控。",
        common_pitfall="scorecard 不是上线批准；shadow candidate 仍需要 OPE、holdout/A/B、rollback 和 artifact refresh。",
        ui_location="Evidence Dashboard / Agent",
        evidence="reports/pilot_readiness_scorecard_latest.json; docs/DEEPUplift_PILOT_READINESS_SCORECARD.md",
    ),
    GlossaryTerm(
        term="pilot experiment plan",
        category="governance",
        short_cn="把 readiness gate 翻译成下一步可执行实验：推荐命令、观察指标、预期 artifact、pass gate、fail action 和 claim upgrade。",
        formula="pilot_experiment = readiness_gate -> command + metrics + artifacts + pass_gate + fail_action + claim_upgrade",
        why_it_matters="它让面试官和评审能看到系统不是只打分，而是知道下一步该跑什么、怎么看结果、什么时候升级或降级 claim。",
        common_pitfall="plan 不是实验结果；只有命令执行后生成 artifact，并通过 validator，claim 才能升级。",
        ui_location="Evidence Dashboard / Agent",
        evidence="reports/pilot_experiment_plan_latest.json; docs/DEEPUplift_PILOT_EXPERIMENT_PLAN.md",
    ),
    GlossaryTerm(
        term="pilot command smoke",
        category="governance",
        short_cn="对 Pilot Experiment Plan 里的推荐命令做小样本安全执行，验证 runner 路径真的能跑。",
        formula="command_smoke = sampled(pilot_experiments) + tiny_rows + no_update_latest -> runner_artifacts",
        why_it_matters="它把“计划能跑”升级成“抽样命令已执行过”，同时用隔离 prefix 防止覆盖主 benchmark evidence。",
        common_pitfall="command smoke 只证明命令可执行，不证明模型效果、试点可上线或策略收益为正。",
        ui_location="Evidence Dashboard / Agent",
        evidence="reports/pilot_experiment_command_smoke_latest.json; docs/DEEPUplift_PILOT_EXPERIMENT_COMMAND_SMOKE.md",
    ),
)


CONTEXT_TERMS: dict[str, tuple[str, ...]] = {
    "benchmark": (
        "PEHE",
        "ATE error",
        "QINI",
        "AUUC",
        "policy value",
        "bootstrap CI",
        "evidence manifest",
        "run diff",
        "DESCN",
        "model evidence promotion matrix",
        "model upgrade recipe card",
        "deep model telemetry ablation gate",
        "deep model ablation interpretation",
        "deep model ablation promotion matrix",
        "deep model ablation next experiment plan",
        "deep model ablation command contract",
        "deep model ablation command contract smoke",
    ),
    "evaluation": (
        "ITE",
        "CATE",
        "QINI",
        "AUUC",
        "uplift@K",
        "policy value",
        "bootstrap CI",
        "overlap",
        "OPE",
    ),
    "model_deconstruction": (
        "CATE",
        "DR Learner",
        "CFRNet",
        "DragonNet",
        "EFIN",
        "DESCN",
        "objective diagnostics",
        "algorithm claim ledger",
        "paper reproduction gap ledger",
        "deep model telemetry-benchmark linkage",
        "deep model telemetry ablation gate",
        "deep model ablation interpretation",
        "deep model ablation promotion matrix",
        "deep model ablation next experiment plan",
        "deep model ablation command contract",
        "deep model ablation command contract smoke",
        "evidence manifest",
    ),
    "policy": (
        "policy value",
        "OPE",
        "IPS / SNIPS / DR OPE",
        "ESS",
        "multi-treatment uplift",
        "dose-response",
        "promotion decision",
        "launch gate",
        "promotion launch card",
    ),
    "evidence": (
        "evidence manifest",
        "run diff",
        "readiness gate",
        "Regression Warning Audit",
        "launch gate",
        "promotion decision",
        "promotion launch card",
        "objective diagnostics",
        "algorithm claim ledger",
        "paper reproduction gap ledger",
        "deep model telemetry ablation gate",
        "deep model ablation interpretation",
        "deep model ablation promotion matrix",
        "deep model ablation next experiment plan",
        "next experiment",
        "owner role",
        "bootstrap CI",
        "overlap",
        "ESS",
    ),
}


def glossary_rows(context: str | None = None) -> list[dict[str, str]]:
    terms = GLOSSARY_TERMS
    if context:
        wanted = set(CONTEXT_TERMS.get(context, ()))
        if wanted:
            terms = tuple(term for term in GLOSSARY_TERMS if term.term in wanted)
    return [asdict(term) for term in terms]


def glossary_lookup(term: str) -> dict[str, str] | None:
    normalized = term.strip().lower()
    for item in GLOSSARY_TERMS:
        if item.term.lower() == normalized:
            return asdict(item)
    return None


def glossary_context_names() -> list[str]:
    return sorted(CONTEXT_TERMS)
